CREATE TABLE IF NOT EXISTS Category
(
    ID     Long NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME   varchar(50),
    PARENT LONG,
    CONSTRAINT FK_CATEGORY_CATEGORY FOREIGN KEY (PARENT) REFERENCES Category (ID)
);

INSERT INTO Category(NAME, PARENT)
VALUES ('KADIN', 1);
INSERT INTO Category(NAME, PARENT)
VALUES ('ERKEK', 1);
INSERT INTO Category(NAME, PARENT)
VALUES ('COCUK', 1);